SELECT
ff."DISTANCEGROUP",
ff."NEXTDAYARR",
ff."DEPDELAYGT15",
s."AIRLINECODE",
s."AIRLINENAME",
s."TAILNUM",
s."FLIGHTNUM",
f."TRANSACTIONID",
f."FLIGHTDATE",
f."CRSDEPTIME",
f."DEPTIME",
f."DEPDELAY",
f."TAXIOUT",
f."WHEELSOFF",
f."WHEELSON",
f."TAXIIN",
f."CRSARRTIME",
f."ARRTIME",
f."ARRDELAY",
f."CRSELAPSEDTIME",
f."ACTUALELAPSEDTIME",
ol."AIRPORTCODE" AS "ORIGINAIRPORTCODE",
ol."AIRPORTNAME" AS "ORIGAIRPORTNAME",
ol."CITYNAME" AS "ORIGINCITYNAME",
ol."STATE_ISO" AS "ORIGINSTATE",
ol."STATENAME" AS "ORIGINSTATENAME",
dl."AIRPORTCODE" AS "DESTAIRPORTCODE",
dl."AIRPORTNAME" AS "DESTAIRPORTNAME",
dl."CITYNAME" AS "DESTCITYNAME",
dl."STATE_ISO" AS "DESTSTATE",
dl."STATENAME" AS "DESTSTATENAME"
FROM "FACT_FLIGHTS" ff
LEFT JOIN "DIM_SERVICE" s
USING (service_id)
LEFT JOIN "DIM_FLIGHT" f
USING (flight_id)
LEFT JOIN "DIM_LOCATION" ol
ON ff.origin_location_id = ol.location_id
LEFT JOIN "DIM_LOCATION" dl
ON ff.destination_location_id = dl.location_id